on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: Build and Analyse
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"

      - name: Install dependencies
        run: npm install
       
      - name: npm version
        run: dir C:\hostedtoolcache\windows\node\14.18.3\x64
        
      - name: env
        env:
          npm.dir: 'C:\hostedtoolcache\windows\node\14.18.3\x64'
        run: env
        
      - run: printenv
        
      - id: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: Sri-hari/HarmonyOsSdk@jstest1
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: build\outputs\hap\debug\phone
